# .github/workflows/dispatcher.yml
name: CI Dispatcher

on:
  push:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed-folders: ${{ steps.get_changed_dirs.outputs.folders }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed top-level folders
        id: get_changed_dirs
        run: |
          echo "Fetching changed folders..."
          folders=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | cut -d '/' -f1 | sort -u)
          folders=$(echo "$folders" | tr '\n' ' ')
          echo "Detected folders: $folders"
          echo "folders=$folders" >> "$GITHUB_OUTPUT"

      - name: Trigger folder workflows
        run: |
          for folder in ${{ steps.get_changed_dirs.outputs.folders }}; do
            workflow="${folder}/${folder,,}-workflow.yml"
            if [ -f "$workflow" ]; then
              echo "Triggering $workflow"
              gh workflow run "$workflow"
            else
              echo "No workflow found at $workflow"
            fi
          done
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
